# Generated by Django 5.0.1 on 2024-02-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookcategory_slug'),
        ('transactions', '0004_alter_transaction_balance_after_transaction'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBorrowerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
